### ISSUE TITLE
Building on Ubuntu 12.04 fails

### ISSUE THREAD

**Issue by fschulze** [collective/buildout.python#24]
This ticket now tracks various issues on Ubuntu (#8, #12 and #13).

Since Ubuntu 11.10 it's recommended to use use deadsnake port for old python installation: https://launchpad.net/~fkrull/+archive/deadsnakes

Please don't compile you own Python if you're not able to fix issues in it. Also, Plone does not use Python2.5 only Python 2.4 and Python 2.6. I don't see why it's an issue here.

I think using those packages is better than using this buildout.

**Comment by mjpieters** [comment]
With 12.04 long gone, I’m closing this. There are still issues with 2.4 and 3.2 on Ubuntu 16.04 and 18.04 but those can be tracked in their own issue if I can’t crack those.
