### ISSUE TITLE
Compilation errors with freetype on Ubuntu LTS 14.04, Trusty Tahir

### ISSUE THREAD

**Issue by do3cc** [collective/buildout.python#39]
To fix it, I did what the guy in this mail did not want to do:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=731015#10

create a symlink:
sudo ln  -s /usr/include/freetype2 /usr/include/freetype2/freetype

**Comment by mjpieters** [comment]
Pillow was removed a few years ago now
