### ISSUE TITLE
platform.mac_ver()[0] returns "10.9" on OSX 10.10

### ISSUE THREAD

**Issue by RichardBarrell** [collective/buildout.python#42]
I get a buildout failure when I attempt to use python2.4 on OS X 10.10 to build a Python egg with Extension modules in it, such as PIL.

The exception message looks something like "No eggs found in /var/folders/nd/nz2j950x6gd51bjfj2316y580000gr/T/easy_install-gkyUY8/PIL-1.1.6/egg-dist-tmp-Rkpvi3 (setup script problem?)"

(More detailed explanation in pull request, in just a moment)

**Comment by RichardBarrell** [comment]
Pull request is #43.

I can attempt to pare down a buildout config to demonstrate the failure scenario if needs be? Demoing the issue is a small PITA because it involves isolating a working Python 2.4 / zc.buildout 1.x buildout, but doable.

**Comment by mpeeters** [comment]
The pull request #43 was merged. Thanks !
