### ISSUE TITLE
Buildout fails under Python 2.6 / Centos 6.6

### ISSUE THREAD

**Issue by avolkov** [collective/buildout.python#45]
I'm trying to run buildout under Centos with the standard interpreter and it fails.

    (python_dev)[plone@vm06 buildout.python]$ python -V
    Python 2.6.6

    (python_dev)[plone@vm06 ~]$ pip freeze
    (python_dev)[plone@vm06 ~]$ 
    gi(python_dev)[plone@vm06 ~]$ git clone https://github.com/collective/buildout.python.git
    Initialized empty Git repository in /home/plone/buildout.python/.git/
    remote: Counting objects: 1415, done.
    remote: Total 1415 (delta 0), reused 0 (delta 0), pack-reused 1415
    Receiving objects: 100% (1415/1415), 265.24 KiB, done.
    Resolving deltas: 100% (837/837), done.
    (python_dev)[plone@vm06 ~]$ cd buildout.python/
    (python_dev)[plone@vm06 buildout.python]$ python bootstrap.py 
    Creating directory '/home/plone/buildout.python/bin'.
    Creating directory '/home/plone/buildout.python/parts'.
    Creating directory '/home/plone/buildout.python/eggs'.
    Creating directory '/home/plone/buildout.python/develop-eggs'.
    Generated script '/home/plone/buildout.python/bin/buildout'.

    (python_dev)[plone@vm06 ~]$ cd buildout.python/
    (python_dev)[plone@vm06 buildout.python]$ python bootstrap.py 
    Creating directory '/home/plone/buildout.python/bin'.
    Creating directory '/home/plone/buildout.python/parts'.
    Creating directory '/home/plone/buildout.python/eggs'.
    Creating directory '/home/plone/buildout.python/develop-eggs'.
    Generated script '/home/plone/buildout.python/bin/buildout'.
    (python_dev)[plone@vm06 buildout.python]$ ./bin/buildout 
    /home/plone/.virtualenvs/python_dev/lib/python2.6/site-packages/pkg_resources/__init__.py:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
      stacklevel=1,
    Getting distribution for 'buildout.extensionscripts'.
    zip_safe flag not set; analyzing archive contents...
    Got buildout.extensionscripts 1.0.
    Getting distribution for 'plone.recipe.command'.
    Got plone.recipe.command 1.1.
    Getting distribution for 'hexagonit.recipe.download'.
    Got hexagonit.recipe.download 1.7.
    Getting distribution for 'collective.recipe.cmmi==0.5'.
    Got collective.recipe.cmmi 0.5.
    While:
      Installing.
      Getting section readline.
      Initializing section readline.
      Installing recipe collective.recipe.cmmi.

    An internal error occured due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/buildout.py", line 1683, in main
        getattr(buildout, command)(args)
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/buildout.py", line 439, in install
        [self[part]['recipe'] for part in install_parts]
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/buildout.py", line 987, in __getitem__
        options._initialize()
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/buildout.py", line 1071, in _initialize
        recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/buildout.py", line 1027, in _install_and_load
        allow_hosts=buildout._allow_hosts
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/easy_install.py", line 800, in install
        return installer.install(specs, working_set)
      File "/home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/easy_install.py", line 662, in install
        [requirement] = err
    ValueError: too many values to unpack

Adding debug before line 662 and then running debug comand yields the following results

     > /home/plone/buildout.python/eggs/zc.buildout-1.4.4-py2.6.egg/zc/buildout/easy_install.py(663)install()
    -> [requirement] = err
    (Pdb) err
    DistributionNotFound(Requirement.parse('zc.recipe.cmmi<=1.4.0'), set(['collective.recipe.cmmi']))
    (Pdb) (a, b) = err
    (Pdb) print a
    zc.recipe.cmmi<=1.4.0
    (Pdb) print b
    set(['collective.recipe.cmmi'])
    (Pdb) (c, ) = err
    *** ValueError: too many values to unpack

It looks like DistributionNotFound error returns a tuple instead of a single element. or easy_install.py in zc.buldout-1.4.4 should be able to accept tuples.

    (Pdb) err.__class__
    <class 'pkg_resources.DistributionNotFound'>
    (Pdb) import inspect
    (Pdb) inspect.getsourcefile(err.__class__)
    '/home/plone/.virtualenvs/python_dev/lib/python2.6/site-packages/pkg_resources/__init__.py'

My guess is package pin is missing somewhere.

**Comment by avolkov** [comment]
Replacing 

     [requirement] = err 

with 

     requirement = err[0]

Fixes the problem.

**Comment by gotcha** [comment]
which version of setuptools are you using ?

**Comment by avolkov** [comment]
I'm running version 15.2

    (python_dev)[plone@vm06 setuptools]$ python
    Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pkg_resources
    >>> pkg_resources.get_distribution('setuptools')
    setuptools 15.2 (/home/plone/.virtualenvs/python_dev/lib/python2.6/site-packages)

**Comment by gotcha** [comment]
It is not surprising that zc.buildout 1.4.4 is not supported by setuptools 15.2.

What is responsible of pinning zc.buildout to 1.4.4 ?

**Comment by avolkov** [comment]
Actually I installed setuptools in virtualenv from which I'm installing buildout. I had some problems with default version of setuptools that caused me to upgrade, but I no longer can reproduce the issue.

**Comment by dtordable** [comment]
Hmm what versión of buildout are you installing? Get plone one that is not
the final one ...

**Comment by gotcha** [comment]
@avolkov I guess this issue can be closed. Ok for you ?

**Comment by avolkov** [comment]
@gotcha  Yes thank you.

**Comment by colinsauce** [comment]
thanks @avolkov . I hit this same thing on Python 2.7.5 / Mac 10.9.3 and your fix above got me going.

**Comment by chrismattmann** [comment]
I also ran into this error on CentOS. Is there a fix rather than the patch above?

**Comment by mauritsvanrees** [comment]
@chrismattmann I have added pull request #48 that fixes this by pinning setuptools to a low version. That would be the best way to fix it I think. Can you see if this works for you?

**Comment by chrismattmann** [comment]
@mauritsvanrees #48 fixes it for me!

**Comment by mauritsvanrees** [comment]
I have just now merged it.
