### ISSUE TITLE
VersionConflict setuptools

### ISSUE THREAD

**Issue by almeidajeff** [collective/buildout.python#54]
when I run

```
python bootstrap.py 
```
It shows the error VersionConflict

```
VersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools==1.4.2'))
```
This happened on a Linux Ubuntu 14.04.1 LTS environment
I ended up solving running the command:

```
sudo easy_install setuptools==1.4.2
```

It's correct ?

**Comment by mauritsvanrees** [comment]
That should be fine yes. It depends a lot per system whether a command like that is needed.  The bootstrap command *should* pull 1.4.2 in just fine, but it might fail for various reasons.
