### ISSUE TITLE
Backport macOS 10.12 build fixes for 2.7

### ISSUE THREAD

**Issue by mjpieters** [collective/buildout.python#58]
Because Quicktime.h is gone, 32-bit Python builds now fail. See https://bugs.python.org/issue27806 for the fix applied to 2.7; this should be backported to 2.4-2.6.

**Comment by fschulze** [comment]
Python 2.6 seems to work for me on Sierra.

I looked into backporting the fix to 2.4 and 2.5, it's possible, but tedious, because the files have too many differences to just fix up the patch. One has to redo it manually.

**Comment by mpeeters** [comment]
I am currently working on a backport of the patch for python 2.4.

I will do a PR when it's done

**Comment by mauritsvanrees** [comment]
Apparently 2.6 is fine without a patch, and for 2.4 and 2.5 the patch has been backported. Closing.
