### ISSUE TITLE
Building on old macOS causes TLS error

### ISSUE THREAD

**Issue by fschulze** [collective/buildout.python#83]
Due to TLS 1.2 only support on PyPI one currently can't bootstrap on older macOS. This also affects current Travis environments.

Bootstrapping manually reveals that zc.buildout 1.4.4 doesn't work either. I haven't tested further yet if recent zc.buildout would work. My guess is no. Switching is also complicated by our use of colons in section names, which would have to be changed.

cc @mjpieters @hannosch

**Comment by fschulze** [comment]
So my guess is that one can't use this buildout without homebrew or similar anymore.

**Comment by fschulze** [comment]
I dug deeper and newer versions of zc.buildout wouldn't work either, as they rely on setuptools, which relies on urllib2 from system Python (in my case 2.7.10 using OpenSSL 0.9.8zh), which doesn't support TLS 1.2.

**Comment by fschulze** [comment]
Is curl or wget working with pypi there? One could create a shell script bootstrap with that.

**Comment by mauritsvanrees** [comment]
Nope, not even `curl` to pypi.org is working on that old Suse server, so it is not something Python specific. We have asked them to create a new server.

**Comment by mjpieters** [comment]
I'm closing this too, as there is no way for me to reproduce this without at least knowing how old a MacOS we are talking about here.
