### ISSUE TITLE
Cannot download extensions

### ISSUE THREAD

**Issue by mcdonc** [collective/buildout.python#85]
After running bootstrap in a fresh checkout of buildout.python as of today:

```
$ bin/buildout
Getting distribution for 'buildout.extensionscripts'.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'buildout.extensionscripts'.
Error: Couldn't find a distribution for 'buildout.extensionscripts'.
```

It's indeed in the PyPI index.  I tried changing zc.buildout.easy_install from:

```
default_index_url = os.environ.get(
    'buildout-testing-index-url',
    'http://pypi.python.org/simple',
    )
```

to

```
default_index_url = os.environ.get(
    'buildout-testing-index-url',
    'https://pypi.org/simple/',
    )
```

But no dice.  I'm gonna guess this is fixed in later 2.X versions of buildout in combination with "new" PyPI but....

**Comment by mpeeters** [comment]
I have the same issue on my new Mac with OS X Mojave and it seems related to OS X : https://travis-ci.org/collective/buildout.python/jobs/472114783

**Comment by daggelpop** [comment]
Hello, I have the same problem on Ubuntu 18.04 (Python 2.7.15rc1).

**Comment by mpeeters** [comment]
I will have a look on this problem ASAP

**Comment by mpeeters** [comment]
I fix this problem on OS X Mojave by installing headers :
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

**Comment by mjpieters** [comment]
That sounds like an unlikely fix; the SDK headers won't help buildout load packages from PyPI.

**Comment by mjpieters** [comment]
I've added a GitHub Actions workflow, and bootstrapping actually works _on Ubuntu 16.04_. Building 2.4 and 3.2 fails as those versions can't cope with the newer OpenSSL versions available, but it's a step further than we were before.

Bootstrapping on Ubuntu 18.04 and MacOS, not so much. I'll see what I can do to improve this.

**Comment by mjpieters** [comment]
In fact, the 16.04 builds [actually tell us what is happening](https://github.com/collective/buildout.python/runs/674682593?check_suite_focus=true#step:5:16):

> /usr/lib/python2.7/dist-packages/pkg_resources/\_\_init\_\_.py:187: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.

This warning was created just for buildout, see the [8.01 setuptools release notes](https://setuptools.readthedocs.io/en/latest/history.html#id541):

> * [Issue #296](https://github.com/pypa/setuptools/issues/296): Restore support for iteration over parse_version result, but deprecated that usage with a warning. Fixes failure with buildout.

The deprecation was finally enacted in [version 39.0](https://setuptools.readthedocs.io/en/latest/history.html#v39-0-0). Using a virtualenv Python with `pip install -f 'setuptools<39'` indeed makes things work again.

**Comment by chrismattmann** [comment]
interesting so if I use the old setuptools like https://github.com/collective/buildout.python/commit/a721d1e7306a6fc6c6f57e5c9de15e77dc46b262 that's a possible workaround?

**Comment by mjpieters** [comment]
Resolved in 707b60cd9d4f0ce6844392a7b555340c89011098

**Comment by mjpieters** [comment]
> interesting so if I use the old setuptools like [a721d1e](https://github.com/collective/buildout.python/commit/a721d1e7306a6fc6c6f57e5c9de15e77dc46b262) that's a possible workaround?

It was only a stopgap measure; the real fix was to install a local egg of setuptools at bootstrap time. That way only this project is stuck with ageing versions, not your other Python projects.

**Comment by chrismattmann** [comment]
awesome @mjpieters i will try it out today!
