### ISSUE TITLE
Require hashes

### ISSUE THREAD

**Issue by brandsimon** [collective/buildout.python#87]
Pip install supports hashes in its requirements file to make sure you install the exact same version everywhere. Is it possible to use something similar with buildout? (I am not talking about version pinning, really hash validation)

**Comment by mauritsvanrees** [comment]
Not as far as I know, but that would be something to ask in https://github.com/buildout/buildout.

**Comment by brandsimon** [comment]
@mauritsvanrees Great, thank you, I will ask there
