### ISSUE TITLE
bootstrap.py contains dead links

### ISSUE THREAD

**Issue by pgrunewald** [collective/buildout.python#95]
The current version of bootstrap.py seems to be outdated as it contains an URL which leads to 404. Upon calling the URL myself (hint: I would not recommend that), was redirected to a spam site!

See the traceback as below:

> [paul@paul-work buildout.python]$ python2 bootstrap.py 
> Traceback (most recent call last):
>   File "bootstrap.py", line 76, in <module>
>     exec(urlopen('http://python-distribute.org/distribute_setup.py').read(), ez)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 404: Not Found

I am running Python2.7.18 with the current Manjaro Linux.

**Comment by mjpieters** [comment]
Yeah, distribute_setup.py is long, long dead. I'll see how to best go about making this work again.

FWIW, it 'works' on Github Actions, where the `python` command is Python 2.7.12.

**Comment by mjpieters** [comment]
Actually, looking at your traceback and the code, you are not using the `bootstrap.py` file as included in this repo, so this doesn't appear to be applicable here.

I _do_ have to rip out the `distribute` switch and codepath, but that's not the default.
